apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service-deployment
spec:
  selector:
    matchLabels:
      app: config-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service-deployment
    spec:
      containers:
        - name: config-service
          image: nerearuiz3/config-service-image
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-service-service
  labels:
    app: config-service-service
spec:
  selector:
    app: config-service-deployment
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort