apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-deployment
  labels:
    app: eureka-service-deployment
spec:
  selector:
    matchLabels:
      app: eureka-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service-deployment
    spec:
      containers:
        - name: eureka-service
          image: nerearuiz3/eureka-service-image
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-service
  labels:
    app: eureka-service-service
spec:
  selector:
    app: eureka-service-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 32089
  type: ClusterIP