apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluacion-service-deployment
  labels:
    app: evaluacion-service-deployment
spec:
  selector:
    matchLabels:
      app: evaluacion-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: evaluacion-service-deployment
    spec:
      containers:
        - name: evaluacion-service
          image: nerearuiz3/evaluacion-service-image
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_EVALUACION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_EVALUACION
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_EVALUACIONES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_EVALUACIONES