apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service-deployment
    spec:
      containers:
        - name: gateway-service
          image: nerearuiz3/gateway-service-image
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service-service:8761/eureka/
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  labels:
    app: gateway-service-service
spec:
  selector:
    app: gateway-service-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer