apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  DB_ROOT_PASSWORD: cHJlc3RhYmFuY28=
  DB_USER_CLIENTES: cHJlc3RhYmFuY28=
  DB_PASSWORD_CLIENTES: cHJlc3RhYmFuY28=
  DB_USER_CREDITOS: cHJlc3RhYmFuY28=
  DB_PASSWORD_CREDITOS: cHJlc3RhYmFuY28=
  DB_USER_EVALUACIONES: cHJlc3RhYmFuY28=
  DB_PASSWORD_EVALUACIONES: cHJlc3RhYmFuY28=
  DB_USER_SIMULACION: cHJlc3RhYmFuY28=
  DB_PASSWORD_SIMULACION: cHJlc3RhYmFuY28=
  DB_USER_SEGUIMIENTO: cHJlc3RhYmFuY28=
  DB_PASSWORD_SEGUIMIENTO: cHJlc3RhYmFuY28=