apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitud-service-deployment
  labels:
    app: solicitud-service-deployment
spec:
  selector:
    matchLabels:
      app: solicitud-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: solicitud-service-deployment
    spec:
      containers:
        - name: solicitud-service
          image: nerearuiz3/solicitud-service-image
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_SOLICITUD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_SOLICITUD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_SOLICITUD
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_SOLICITUD