apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-service-deployment
  labels:
    app: usuario-service-deployment
spec:
  selector:
    matchLabels:
      app: usuario-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: usuario-service-deployment
    spec:
      containers:
        - name: usuario-service
          image: nerearuiz3/usuario-service-image
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_USUARIO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_USUARIO
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_CLIENTES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_CLIENTES