server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://192.168.49.2:32089/eureka
  instance:
    preferIpAddress: true
    hostname: 192.168.49.2
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: simulacionCredito-service
            uri: lb://simulacionCredito-service
            predicates:
              - Path=/api/v1/simulacion-credito/**
          - id: usuario-service
            uri: lb://usuario-service
            predicates:
              - Path=/api/v1/cliente/**
          - id: solicitud-service
            uri: lb://solicitud-service
            predicates:
              - Path=/api/v1/credito/**
          - id: evaluacion-service
            uri: lb://evaluacion-service
            predicates:
              - Path=/api/v1/evaluacion/**
          - id: seguimiento-service
            uri: lb://seguimiento-service
            predicates:
              - Path=/api/v1/seguimiento/**