server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: simulacionCredito-service
          uri: lb://simulacionCredito-service:8090
          predicates:
            - Path=/api/v1/simulacion-credito/**
        - id: usuario-service
          uri: lb://usuario-service:8091
          predicates:
            - Path=/api/v1/cliente/**
        - id: solicitud-service
          uri: lb://solicitud-service:8092
          predicates:
            - Path=/api/v1/credito/**